import { Profile, Project, Task, NotificationItem, ActivityLog } from '../types/taskflow';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-01',
    email: 'alex.rivera@taskflow.dev',
    full_name: 'Alex Rivera',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'project_manager',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'user-02',
    email: 'sarah.chen@taskflow.dev',
    full_name: 'Sarah Chen',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'developer',
    created_at: '2026-01-16T10:00:00Z',
  },
  {
    id: 'user-03',
    email: 'marcus.vance@taskflow.dev',
    full_name: 'Marcus Vance',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'designer',
    created_at: '2026-02-01T08:30:00Z',
  },
  {
    id: 'user-04',
    email: 'elena.rostova@taskflow.dev',
    full_name: 'Elena Rostova',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'developer',
    created_at: '2026-02-10T11:15:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    name: 'Mobile App v2.0',
    description: 'React Native & Supabase migration with real-time offline sync and push alerts.',
    color: '#6366f1',
    icon: 'Smartphone',
    owner_id: 'user-01',
    created_at: '2026-03-01T10:00:00Z',
    members_count: 4,
  },
  {
    id: 'proj-02',
    name: 'Brand Redesign & Design System',
    description: 'Refined UI tokens, NativeWind typography scale, and dark mode palette.',
    color: '#0ea5e9',
    icon: 'Palette',
    owner_id: 'user-03',
    created_at: '2026-03-05T14:30:00Z',
    members_count: 3,
  },
  {
    id: 'proj-03',
    name: 'Cloud Infrastructure & RLS',
    description: 'PostgreSQL row-level security hardening, automated backup triggers, and replication.',
    color: '#10b981',
    icon: 'Database',
    owner_id: 'user-02',
    created_at: '2026-03-10T08:45:00Z',
    members_count: 2,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    project_id: 'proj-01',
    title: 'Configure Supabase Auth & Google OAuth callback',
    description: 'Set up Supabase client with PKCE flow in Expo. Add deep link handler for com.taskflow.app://auth/callback to receive the session access token.',
    status: 'done',
    priority: 'high',
    due_date: '2026-09-22T17:00:00Z',
    assignee_id: 'user-02',
    assignee: INITIAL_PROFILES[1],
    created_by: 'user-01',
    position: 0,
    subtasks: [
      { id: 'sub-1', task_id: 'task-101', title: 'Register OAuth Client in Google Cloud Console', is_completed: true, position: 0, created_at: '2026-09-20T10:00:00Z' },
      { id: 'sub-2', task_id: 'task-101', title: 'Add schema redirect in app.json', is_completed: true, position: 1, created_at: '2026-09-20T10:05:00Z' },
      { id: 'sub-3', task_id: 'task-101', title: 'Implement onAuthStateChange listener in auth store', is_completed: true, position: 2, created_at: '2026-09-20T10:10:00Z' },
    ],
    attachments: [
      {
        id: 'att-1',
        task_id: 'task-101',
        file_name: 'oauth_architecture_flow.png',
        file_size: 245000,
        file_type: 'image/png',
        file_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80',
        uploaded_by: 'Sarah Chen',
        created_at: '2026-09-21T11:00:00Z',
      },
    ],
    created_at: '2026-09-20T09:00:00Z',
    updated_at: '2026-09-22T16:30:00Z',
  },
  {
    id: 'task-102',
    project_id: 'proj-01',
    title: 'Build Kanban Board with tactile touch drag-and-drop',
    description: 'Create smooth column scrolling, auto-scroll when dragging near viewport edges, and status update optimistic state mutations.',
    status: 'in_progress',
    priority: 'urgent',
    due_date: '2026-09-25T18:00:00Z',
    assignee_id: 'user-01',
    assignee: INITIAL_PROFILES[0],
    created_by: 'user-01',
    position: 0,
    subtasks: [
      { id: 'sub-4', task_id: 'task-102', title: 'Set up HTML5 drag and drop events on web', is_completed: true, position: 0, created_at: '2026-09-23T09:00:00Z' },
      { id: 'sub-5', task_id: 'task-102', title: 'Implement PanResponder / Reanimated gesture for React Native', is_completed: false, position: 1, created_at: '2026-09-23T09:05:00Z' },
      { id: 'sub-6', task_id: 'task-102', title: 'Add haptic feedback on card drop', is_completed: false, position: 2, created_at: '2026-09-23T09:10:00Z' },
      { id: 'sub-7', task_id: 'task-102', title: 'Sync column reorders with Supabase position column', is_completed: false, position: 3, created_at: '2026-09-23T09:15:00Z' },
    ],
    attachments: [],
    created_at: '2026-09-22T10:00:00Z',
    updated_at: '2026-09-24T08:00:00Z',
  },
  {
    id: 'task-103',
    project_id: 'proj-01',
    title: 'Implement sub-task checklists with animated progress bar',
    description: 'Allow users to add sub-items with checkbox toggles, instant progress percentage recalculation, and keyboard shortcuts (Enter to add new).',
    status: 'in_progress',
    priority: 'medium',
    due_date: '2026-09-26T15:00:00Z',
    assignee_id: 'user-04',
    assignee: INITIAL_PROFILES[3],
    created_by: 'user-01',
    position: 1,
    subtasks: [
      { id: 'sub-8', task_id: 'task-103', title: 'Database schema for subtasks table with foreign keys', is_completed: true, position: 0, created_at: '2026-09-23T11:00:00Z' },
      { id: 'sub-9', task_id: 'task-103', title: 'Subtask creation API with optimistic response', is_completed: true, position: 1, created_at: '2026-09-23T11:05:00Z' },
      { id: 'sub-10', task_id: 'task-103', title: 'Inline editing on double click / tap', is_completed: false, position: 2, created_at: '2026-09-23T11:10:00Z' },
    ],
    attachments: [],
    created_at: '2026-09-23T10:30:00Z',
    updated_at: '2026-09-24T09:15:00Z',
  },
  {
    id: 'task-104',
    project_id: 'proj-01',
    title: 'Push notification engine for upcoming deadline alerts',
    description: 'Implement automated check for tasks due within 24 hours. Send Expo push notifications to registered user device tokens and notify in-app center.',
    status: 'todo',
    priority: 'high',
    due_date: '2026-09-27T12:00:00Z',
    assignee_id: 'user-02',
    assignee: INITIAL_PROFILES[1],
    created_by: 'user-01',
    position: 0,
    subtasks: [
      { id: 'sub-11', task_id: 'task-104', title: 'Expo-notifications token registration flow', is_completed: false, position: 0, created_at: '2026-09-24T08:00:00Z' },
      { id: 'sub-12', task_id: 'task-104', title: 'Web browser Notification API fallbacks', is_completed: false, position: 1, created_at: '2026-09-24T08:05:00Z' },
      { id: 'sub-13', task_id: 'task-104', title: 'Cron job or Supabase Edge function for scheduled reminders', is_completed: false, position: 2, created_at: '2026-09-24T08:10:00Z' },
    ],
    attachments: [],
    created_at: '2026-09-24T07:30:00Z',
    updated_at: '2026-09-24T07:30:00Z',
  },
  {
    id: 'task-105',
    project_id: 'proj-01',
    title: 'File attachment upload with image preview & metadata',
    description: 'Integrate Supabase Storage bucket `task-attachments`. Generate presigned URLs, render image thumbnails, and compute human-readable file sizes.',
    status: 'review',
    priority: 'medium',
    due_date: '2026-09-24T20:00:00Z',
    assignee_id: 'user-03',
    assignee: INITIAL_PROFILES[2],
    created_by: 'user-01',
    position: 0,
    subtasks: [
      { id: 'sub-14', task_id: 'task-105', title: 'Create public/private storage bucket with RLS', is_completed: true, position: 0, created_at: '2026-09-22T14:00:00Z' },
      { id: 'sub-15', task_id: 'task-105', title: 'Image compressor before upload', is_completed: true, position: 1, created_at: '2026-09-22T14:20:00Z' },
      { id: 'sub-16', task_id: 'task-105', title: 'Attachment removal & storage purge', is_completed: true, position: 2, created_at: '2026-09-23T15:00:00Z' },
    ],
    attachments: [
      {
        id: 'att-2',
        task_id: 'task-105',
        file_name: 'spec_document_v2.pdf',
        file_size: 1048576,
        file_type: 'application/pdf',
        file_url: 'https://example.com/spec_document_v2.pdf',
        uploaded_by: 'Marcus Vance',
        created_at: '2026-09-23T15:30:00Z',
      },
    ],
    created_at: '2026-09-22T13:00:00Z',
    updated_at: '2026-09-24T09:00:00Z',
  },
  {
    id: 'task-106',
    project_id: 'proj-01',
    title: 'Dark / Light theme automatic system sync & toggle',
    description: 'Provide system theme detection using NativeWind / Tailwind `useColorScheme`. Allow persistent manual override in local storage.',
    status: 'done',
    priority: 'low',
    due_date: '2026-09-21T18:00:00Z',
    assignee_id: 'user-03',
    assignee: INITIAL_PROFILES[2],
    created_by: 'user-01',
    position: 1,
    subtasks: [
      { id: 'sub-17', task_id: 'task-106', title: 'Configure Tailwind v4 dark class strategy', is_completed: true, position: 0, created_at: '2026-09-21T09:00:00Z' },
      { id: 'sub-18', task_id: 'task-106', title: 'Add theme toggle button with smooth icon transition', is_completed: true, position: 1, created_at: '2026-09-21T09:30:00Z' },
    ],
    attachments: [],
    created_at: '2026-09-21T08:30:00Z',
    updated_at: '2026-09-21T17:45:00Z',
  },
  {
    id: 'task-107',
    project_id: 'proj-02',
    title: 'Audit mobile touch targets and 44px hitbox margins',
    description: 'Ensure all buttons, tabs, chevrons, and checkboxes meet Apple HIG & Material 3 minimum 44x44px touch targets.',
    status: 'todo',
    priority: 'medium',
    due_date: '2026-09-28T16:00:00Z',
    assignee_id: 'user-03',
    assignee: INITIAL_PROFILES[2],
    created_by: 'user-03',
    position: 1,
    subtasks: [
      { id: 'sub-19', task_id: 'task-107', title: 'Audit Kanban column action buttons', is_completed: false, position: 0, created_at: '2026-09-24T08:00:00Z' },
      { id: 'sub-20', task_id: 'task-107', title: 'Audit bottom tab bar tap boundaries', is_completed: false, position: 1, created_at: '2026-09-24T08:05:00Z' },
    ],
    attachments: [],
    created_at: '2026-09-24T08:00:00Z',
    updated_at: '2026-09-24T08:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-01',
    title: 'Deadline Approaching',
    message: 'Task "Build Kanban Board with tactile touch drag-and-drop" is due in 24 hours.',
    type: 'deadline',
    task_id: 'task-102',
    is_read: false,
    created_at: '2026-09-24T08:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-01',
    title: 'Task Moved to Review',
    message: 'Marcus Vance moved "File attachment upload with image preview" to In Review.',
    type: 'status_change',
    task_id: 'task-105',
    is_read: false,
    created_at: '2026-09-24T09:00:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'user-01',
    title: 'New Subtask Completed',
    message: 'Elena Rostova marked "Subtask creation API with optimistic response" as done.',
    type: 'status_change',
    task_id: 'task-103',
    is_read: true,
    created_at: '2026-09-23T11:05:00Z',
  },
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'act-1',
    task_id: 'task-105',
    task_title: 'File attachment upload with image preview & metadata',
    user_name: 'Marcus Vance',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action: 'moved task from In Progress to Review',
    timestamp: '25 minutes ago',
  },
  {
    id: 'act-2',
    task_id: 'task-103',
    task_title: 'Implement sub-task checklists with animated progress bar',
    user_name: 'Elena Rostova',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    action: 'completed subtask "Subtask creation API"',
    timestamp: '2 hours ago',
  },
  {
    id: 'act-3',
    task_id: 'task-102',
    task_title: 'Build Kanban Board with tactile touch drag-and-drop',
    user_name: 'Alex Rivera',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'updated priority to Urgent',
    timestamp: '4 hours ago',
  },
  {
    id: 'act-4',
    task_id: 'task-101',
    task_title: 'Configure Supabase Auth & Google OAuth callback',
    user_name: 'Sarah Chen',
    user_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    action: 'marked task as Done',
    timestamp: 'Yesterday',
  },
];
